[package]
name = "counter_on_native_solana"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.5"
borsh-derive = "1.5.5"
solana-program = "2.2.1"

[dev-dependencies]
solana-program-test = "2.2.0"
solana-sdk = "2.2.1"